controller_list:
  - name: "arm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - carriageJ
      - midarm1J
      - midarm2J
      - wrist1J
      - wrist2J
      - EEbaseJ
