# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: robot_arm
  joint_model_group_pose: front
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - carriageJ
    - midarm1J
    - midarm2J
    - wrist1J
    - wrist2J
    - EEbaseJ
    - RLink1J
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - carriageJ
    - midarm1J
    - midarm2J
    - wrist1J
    - wrist2J
    - EEbaseJ
  gains:
    carriageJ:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    midarm1J:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    midarm2J:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist1J:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist2J:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    EEbaseJ:
      p: 100
      d: 1
      i: 1
      i_clamp: 1