joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - carriageJ
    - midarm1J
    - midarm2J
    - wrist1J
    - wrist2J
    - EEbaseJ
  constraints:
    carriageJ: {trajectory: 50, goal: 50}
    midarm1J: {trajectory: 50, goal: 50}
    midarm2J: {trajectory: 50, goal: 50}
    wrist1J: {trajectory: 50, goal: 50}
    wrist2J: {trajectory: 50, goal: 50}
    EEbaseJ: {trajectory: 50, goal: 50}
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - carriageJ
    - midarm1J
    - midarm2J
    - wrist1J
    - wrist2J
    - EEbaseJ
